#!/usr/bin/env Rscript
# Author: OLP/01/2022
# Usage: Getting metadata for ngs file
# Parameter: Run Name ;  i.e. Rscript ngs.R UT-VH0770-230212
# last modified on 22/09/12


library("easypackages");libraries("grid","rbin","data.table","progress","XML","xml2","seqinr","data.table")
sup <- suppressPackageStartupMessages
sup(library(lubridate));sup(library(tidyverse));options("width"=300)

args = commandArgs(trailingOnly=T)
if(nchar(args[1])==17){date<-ymd(substr(args[1], 12, 17))} else{date<-ymd(substr(args[1], 11, 16))};date
runPath <-paste('/Volumes/NGS/Analysis/covidseq',args[1],sep="/")
df1 = read.csv(paste(runPath,"covidseq_output/Logs_Intermediates/SampleSheetValidation/SampleSheet_Intermediate.csv",sep = "/"))
x = apply(df1, 1, function(x) {any(grepl(x, pattern = "Patient")) });
M<-df1[x, ][,c(1,2)]; 
M<-cbind(M, paste(M$X.Header.,args[1],sep = "-"))
colnames(M)<-c("Sample_Accession","runName","fileName");
cat(" Detected ", length(M$Sample_Accession), " patient's samples")
head(M,10)

# Getting Pangolin lineage ( cecret must be ran first)
# ====================
pango<-read.csv(paste(runPath,"CecretPangolin/pangolin/lineage_report.csv",sep ="/"))[,c("taxon","lineage")]
var <-paste('',args[1],sep='-'); head(var)
pango<-pango %>% mutate_at("taxon", str_replace, var, "")
M<-merge(M,pango, by.x="Sample_Accession", by.y= "taxon", all.x=T)
M$lineage[is.na(M$lineage)]= "Not able to be sequenced"

# Searching LIMS for collection dates (NGS and All...)
# ========================
cat(crayon::bold("Please wait, serching UPHL-LIMS","\n"))
cat(crayon::bold("1. From NGS_Covid","\n"))
NGS_covid<-rownames(fileSnapshot("/Volumes/IDGenomics_NAS/COVID/daily_metadata/lims/",
                                 pattern=glob2rx("NGS*.csv"))$info[which.max(fileSnapshot("/Volumes/IDGenomics_NAS/COVID/daily_metadata/lims/",
                                                                                          pattern=glob2rx("NGS*.csv"))$info$mtime),])
NGS_covid <- fread(paste('/Volumes/IDGenomics_NAS/COVID/daily_metadata/lims/',NGS_covid,sep=""), 
                   select = c("submitterId","sampleNumber","lastName","firstName","DOB","collectionDate")) 
head(NGS_covid); 
NGS_covid1<-select(NGS_covid,c("sampleNumber","lastName","firstName","DOB","collectionDate"))
NGS_covid1$sampleNumber<-as.character(NGS_covid1$sampleNumber); 
NGS_covid2<-select(NGS_covid,c("submitterId","lastName","firstName","DOB","collectionDate"))
colnames(NGS_covid2)[1]<-("sampleNumber")
NGS_covid<-bind_rows(NGS_covid1,NGS_covid2)
head(NGS_covid)
NGS_covid$DOB<-as.character(NGS_covid$DOB)
NGS_covid$collectionDate<-as.character(NGS_covid$collectionDate)

cat(crayon::bold("2. From All_nocovid_NoNGS","\n"))
All_nocovid<-rownames(fileSnapshot("/Volumes/IDGenomics_NAS/COVID/daily_metadata/lims/",
                                   pattern=glob2rx("All*.csv"))$info[which.max(fileSnapshot("/Volumes/IDGenomics_NAS/COVID/daily_metadata/lims/",
                                                                                            pattern=glob2rx("All*.csv"))$info$mtime),])
locus<-paste('/Volumes/IDGenomics_NAS/COVID/daily_metadata/lims/',All_nocovid,sep="")
locus

df <- read.table(locus,header=TRUE,sep=",", stringsAsFactors=FALSE,comment.char="", fill = T,quote="\"")
All_ncovid_NoNGS<-data.frame(df$sampleNumber,df$lastName, df$firstName, df$DOB,df$collectionDate)
head(All_ncovid_NoNGS,10)
dim(All_ncovid_NoNGS)
dim(NGS_covid)

lapply(NGS_covid, class)
lapply(All_ncovid_NoNGS, class)
# Generating a LIMS for this run
# ========================
head(NGS_covid)
colnames(All_ncovid_NoNGS)<-c("sampleNumber","lastName", "firstName", "DOB","collectionDate")
head(All_ncovid_NoNGS)
LIMS<-rbind(NGS_covid,All_ncovid_NoNGS)
head(LIMS, 20)
colnames(LIMS)<-c("sampleNumber","lastName", "firstName", "DOB","collectionDate")
dim(LIMS)
head(M)
ngs<-merge(M,LIMS, by.x ="Sample_Accession",by.y="sampleNumber", x.all = T)
ngs<-cbind(ngs,'Name of facility performing the test'='UPHL', 'ordering facility' ='UHPL','Name or description of the test ordered'="SARS-CoV-2 Whole Genome Sequencing",
            'lab test date'=date,'lab test status' ="preliminary")
ngs_file<-select(ngs,"lastName",	"firstName",	"DOB",	"Name of facility performing the test","Name or description of the test ordered",
                 "collectionDate","sampleNumber","lab test date","lab test status",	"Test result",	"ordering facility")

head(ngs)
ngs_file<-select(ngs,"lastName",	"firstName",	"DOB",	"Name of facility performing the test","Name or description of the test ordered","collectionDate", "Sample_Accession",
                 ,"lab test date",,"lab test status","lineage",	"ordering facility")


ngs_file[is.na(ngs_file)] <- ""
head(ngs_file)
colnames(ngs_file)[7]<-c("sampleNumber");colnames(ngs_file)[10]<-c("Test result")

# Storing ngs file at /Volumes/NGS/Analysis/covidseq/ $runName
# ==========================
d=paste(runPath,'Rsumcovidseq',sep="/")
 dir.create(file.path(d,"" ), recursive = T)
 LL<-paste(substring(Sys.time(), 1,10),substring(Sys.time(), 12,13),substring(Sys.time(), 15,16),substring(Sys.time(), 18,19),sep = "-")
 dx<- paste(paste('ngs',args[1],sep="_"),LL,".csv",sep="")
 dx<-paste(d,dx, sep ='/');write.csv(ngs_file,dx,row.names=F)
 cat(crayon::bold("ngs file is complete and can be found at",d,"\n"))



# Summary file
# ======================
df2 = read.csv(paste(runPath,"CecretPangolin/pangolin/lineage_report.csv",sep ="/"))
df3 = read.table(file = paste(runPath,"covidseq_output/Logs_Intermediates/VirusDetection/kmer/Summary.tsv",sep ="/"), sep = '\t', header = T); 
df4 = read.csv(paste(runPath,"covidseq_output/Logs_Intermediates/FastqGeneration/Reports/Demultiplex_Stats.csv",sep ="/"))
df4<-select(df4, c("SampleID","X..Reads","Mean.Quality.Score..PF."))
var <-paste('',args[1],sep='-'); head(var)
df4<-df4 %>% mutate_at("SampleID", str_replace, var, ""); df4<-df4 %>% rename(Num_reads = 2, Mean_Quality_Score = 3)
dim(df4)
head(df4)

# Random Number Generator for Sample_IDs
# =========================
n<-length(M$Sample_Accession)
RNG<-paste(floor(runif(n, min=99, max=1000)),floor(runif(n, min=99, max=1000)),sep ="")
# Checking for duplicates in RNG
    while(length(RNG)!= length(unique(RNG)))
    { RNG<-paste(floor(runif(n, min=99, max=1000)),floor(runif(n, min=99, max=1000)),sep ="");}
    IDD<-paste("UT-UPHL",substr(args[1], 11, 16),sep="-")
    Sample_ID<-paste(IDD,RNG,sep="")
    df1<-M$Sample_Accession
    summary1<-cbind(df1,Sample_ID); summary1
 head(summary1)

 #join tables: SampleSheet & Combined Lineage Report
#==========================  
var <-paste('',args[1],sep='-');
df2 <-df2 %>% mutate_at("taxon", str_replace, var, "")
df2<-df2[,c("taxon","lineage","scorpio_call")]
df3<-df3 %>% mutate_at("Sample", str_replace, var, "")
df3<-df3[,c("Sample","nTargetsDetected.SARS.CoV2")]
colnames(df3)[2] <- 'sc2_amplicons';#

head(summary1)
summary1<-merge(summary1,df2, by.x="df1", by.y= "taxon", all.x=TRUE)
summary1<-merge(summary1,df3, by.x="df1", by.y= "Sample", all.x=TRUE)
head(df3)

# Reading fasta files for nucleotides count: actg & anbiguous (n)
# ========================
num_actgx<-vector();num_nx<-vector(); pass_fail<-vector()
runPath1 = paste(runPath,"covidseq_output/Sample_Analysis/",sep ="/")
num_actgx = 0; num_nx = 0;
for (i in 1:n){
#i =1 
 sample=summary1$df1[i]; sample; 
  amplicons=summary1$sc2_amplicons[i];amplicons
  if(amplicons >=50)
  {
    Lyapunovv<- Sys.glob(paste(runPath1,sample,"*/*.fasta",sep = ""),dirmark = TRUE)
    a =  str_count(read.fasta(Lyapunovv, as.string = T, forceDNAtolower = T), pattern = "a|c|t|g");num_actgx[i] = a
    b =  str_count(read.fasta(Lyapunovv, as.string = T, forceDNAtolower = T))-a; num_nx[i] = b; pass_fail[i] ="pass"; c = "pass"
  }
  else {# AmpliconThereshold <50,
    a = b =0; num_actgx[i] = 0; num_nx[i] = 0; pass_fail[i] ="fail"; c = "fail"
  }
  cat(sample," \t",a,"\t",b,"\t",c,"\n")
}

df_new <- as.data.frame(cbind(as.character(num_actgx), as.character(num_nx),pass_fail)); 
df_new<-df_new %>% rename(num_actg = 1, num_n = 2)
head(df_new)
summary<-cbind(summary1,df_new);
head(summary)
dim(summary)

# adding more info to the summary file
# ==============================
summary<-merge(summary,df4, by.x = "df1", by.y = "SampleID", all.x = T )
head(summary)
colnames(summary)[1]<-c("SampeNumber")

# Saving file at /Volumes/NGS/Analysis/covidseq/$runName
# ==========================
d=paste(runPath,'Rsumcovidseq',sep="/");dir.create(file.path(d,"" ), recursive = TRUE); p1<-Sys.time()
dx<- paste(d,'/Rcovidseq_summary-',paste0(Sys.Date(),'-',hour(Sys.time()),'-',minute(Sys.time()),'-',second(Sys.time())),".csv",sep=""); 
write.csv(summary,dx,row.names=FALSE)
dx<- paste(d,'/RunParameters-',paste0(Sys.Date(),'-',hour(Sys.time()),'-',minute(Sys.time()),'-',second(Sys.time())),".csv",sep=""); 
write.csv(RunPar,dx,row.names=FALSE)
cat("Summary & run rarameters files are complete and can be found at: ",d,"\n")
